name: ğŸ¿ï¸ ARC-2 fast scaling test

on:
  workflow_dispatch:  # run on demand
    inputs:
      target-scale-set:
        description: "Which scale set to test?"
        type: string
        required: true

jobs:
  hello-world:
    runs-on: ${{ github.event.inputs.target-scale-set }}  # use the set we specify
    strategy:
      matrix:  # generate 25 jobs
        number: [1, 2, 3, 4, 5]
        letter: [a, b, c, d, e]
    steps:
      - name: Hello world  # print a thing, should take a couple seconds to run
        run: |
          echo "Hello world"
          echo "Number: ${{ matrix.number }}"
          echo "Letter: ${{ matrix.letter }}"